---
- name: install prerequisites
  apt:
    name: "{{ prerequisites_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: add apt-key for unifi
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 06E85760C0A52C50
  become: yes

- name: add apt-key mongodb
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    state: present
  become: yes

- name: add apt-key openjdk
  ansible.builtin.apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
  become: yes

- name: add apt-repo unifi
  ansible.builtin.apt_repository:
    repo: deb https://www.ui.com/downloads/unifi/debian {{ unifi_release }} ubiquiti
    state: present
  become: yes

- name: add apt-repo mongodb
  ansible.builtin.apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/{{ mongodb_version }} main
    state: present
  become: yes

- name: add apt-repo openjdk
  ansible.builtin.apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main
    state: present
  become: yes

- name: update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: install packages mongodb openjdk and unifi
  apt:
    name: "{{ main_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes  
